SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_INCLUDE_DIRS += $(PWD)/ $(PWD)/../hdl/
VERILOG_SOURCES += $(PWD)/../hdl/rtclock.v
# use VHDL_SOURCES for VHDL files

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = rtclock

# MODULE is the basename of the Python test file
#MODULE = tb_axi_lite_flip_register
#test_my_design

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
