`define  REG_ID_BITS				31:0
`define  REG_ID_WIDTH				32
`define  REG_ID_DEFAULT				32'h12300003
`define  REG_ID_ADDR				32'h0

`define  REG_VERSION_BITS				31:0
`define  REG_VERSION_WIDTH				32
`define  REG_VERSION_DEFAULT				32'h1
`define  REG_VERSION_ADDR				32'h4

`define  REG_MIN_INTERFRAME_GAP_BITS			31:0
`define  REG_MIN_INTERFRAME_GAP_WIDTH			32
`define  REG_MIN_INTERFRAME_GAP_DEFAULT			32'd21
`define  REG_MIN_INTERFRAME_GAP_ADDR			32'h8

