#!/bin/bash
address="0xa02d0000"
GPIO_DATA_REG_OFFSET=0 ; GPIO_DATA_REG_ADDRESS="0x`printf '%x\n' $((${address}+${GPIO_DATA_REG_OFFSET}))`"
devmem32 $GPIO_DATA_REG_ADDRESS 2
devmem32 $GPIO_DATA_REG_ADDRESS
