`define  REG_ID_BITS				31:0
`define  REG_ID_WIDTH				32
`define  REG_ID_DEFAULT				32'h12345678
`define  REG_ID_ADDR				32'h0

`define  REG_VERSION_BITS				31:0
`define  REG_VERSION_WIDTH				32
`define  REG_VERSION_DEFAULT				32'h1
`define  REG_VERSION_ADDR				32'h4

`define  REG_FLIP_BITS				31:0
`define  REG_FLIP_WIDTH				32
`define  REG_FLIP_DEFAULT				32'h0
`define  REG_FLIP_ADDR				32'hC

`define  REG_CONTROL_BITS			31:0
`define  REG_CONTROL_WIDTH			32
`define  REG_CONTROL_DEFAULT			32'h0
`define  REG_CONTROL_ADDR			32'h10

`define  REG_INTERFRAME_GAP_BITS		31:0
`define  REG_INTERFRAME_GAP_WIDTH		32
`define  REG_INTERFRAME_GAP_DEFAULT		32'hC
`define  REG_INTERFRAME_GAP_ADDR		32'h14

`define  REG_INTERBURST_GAP_BITS		31:0
`define  REG_INTERBURST_GAP_WIDTH		32
`define  REG_INTERBURST_GAP_DEFAULT		32'hC
`define  REG_INTERBURST_GAP_ADDR		32'h18

`define  REG_FRAMES_PER_BURST_BITS		31:0
`define  REG_FRAMES_PER_BURST_WIDTH		32
`define  REG_FRAMES_PER_BURST_DEFAULT		32'h0
`define  REG_FRAMES_PER_BURST_ADDR		32'h1C

`define  REG_TOTAL_FRAMES_BITS			63:0
`define  REG_TOTAL_FRAMES_WIDTH			64
`define  REG_TOTAL_FRAMES_DEFAULT		64'h0
`define  REG_TOTAL_FRAMES_ADDR			32'h20

`define  REG_FRAME_SIZE_BITS		31:0
`define  REG_FRAME_SIZE_WIDTH		32
`define  REG_FRAME_SIZE_DEFAULT		32'h48
`define  REG_FRAME_SIZE_ADDR		32'h44

`define  REG_FRAME_BUF_BITS		31:0
`define  REG_FRAME_BUF_WIDTH		32
`define  REG_FRAME_BUF_DEFAULT		32'h0
`define  REG_FRAME_BUF_ADDR		32'h50

