#!/bin/bash -xe

rm -rf spark/configdone.txt spark/images
rm -rf a b
mkdir -p src/common/project-spec/meta-user/recipes-bsp/u-boot/files
mkdir -p a/ ; cp platform-auto.h.original a/platform-auto.h
mkdir -p b/ ; cp platform-auto.h b/platform-auto.h
diff -Naur platform-auto.h.original platform-auto.h > src/common/project-spec/meta-user/recipes-bsp/u-boot/files/platform-auto.patch || true
cp src/common/project-spec/meta-user/recipes-bsp/u-boot/files/platform-auto.patch spark/project-spec/meta-user/recipes-bsp/u-boot/files/platform-auto.patch
cp platform-auto.h spark/project-spec/meta-user/recipes-bsp/u-boot/files/
./build-petalinux $1
